import os
import boto3
import psycopg2

# Fetch Aurora configuration from environment variables
AURORA_ENDPOINT = os.environ.get("AURORA_ENDPOINT")
DB_REGION = os.environ.get("DB_REGION", "us-east-1")
DB_USER = os.environ.get("DB_USER", "postgres")
DB_NAME = os.environ.get("DB_NAME", "postgres")

TABLES = [
    """
    CREATE TABLE IF NOT EXISTS stops (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 100) PRIMARY KEY,
        transport_id INT,
        gtfs_stop_id TEXT,
        stop_name TEXT,
        stop_lat DOUBLE PRECISION,
        stop_lon DOUBLE PRECISION,
        location_type SMALLINT,
        parent_station TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS routes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 100) PRIMARY KEY,
        transport_id INT,
        gtfs_route_id TEXT,
        route_short_name TEXT,
        route_long_name TEXT,
        route_type SMALLINT,
        route_color TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS calendar (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 100) PRIMARY KEY,
        transport_id INT,
        gtfs_service_id TEXT,
        monday BOOLEAN,
        tuesday BOOLEAN,
        wednesday BOOLEAN,
        thursday BOOLEAN,
        friday BOOLEAN,
        saturday BOOLEAN,
        sunday BOOLEAN,
        start_date TEXT,
        end_date TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS trips (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 100) PRIMARY KEY,
        transport_id INT,
        gtfs_trip_id TEXT,
        gtfs_route_id TEXT,
        gtfs_service_id TEXT,
        trip_headsign TEXT,
        direction_id SMALLINT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS stop_times (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 100) PRIMARY KEY,
        transport_id INT,
        gtfs_trip_id TEXT,
        gtfs_stop_id TEXT,
        arrival_time INT,
        departure_time INT,
        stop_sequence INT,
        pickup_type SMALLINT,
        drop_off_type SMALLINT
    )
    """
]

def main():
    if not AURORA_ENDPOINT:
        print("Error: AURORA_ENDPOINT environment variable not set.")
        return

    # Generate IAM Auth Token
    rds_client = boto3.client('rds', region_name=DB_REGION)
    token = rds_client.generate_db_auth_token(
        DBHostname=AURORA_ENDPOINT,
        Port=5432,
        DBUsername=DB_USER,
        Region=DB_REGION
    )

    print(f"Connecting to Aurora at {AURORA_ENDPOINT}...")
    conn = psycopg2.connect(
        host=AURORA_ENDPOINT,
        port=5432,
        database=DB_NAME,
        user=DB_USER,
        password=token,
        sslmode='require'
    )
    conn.autocommit = True
    cur = conn.cursor()

    for sql in TABLES:
        print("Running:", sql.split("(")[0].strip())
        cur.execute(sql)

    cur.close()
    conn.close()
    print("All tables created successfully in Aurora!")

if __name__ == "__main__":
    main()